version: '3.3'
services:
    db:
        image: postgres:15-alpine3.17
        environment:
          - POSTGRES_USER=${DATABASE_USER}
          - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
          - POSTGRES_DB=${DATABASE_NAME}
          - PGDATA="/data/postgres"
        restart: unless-stopped
        ports:
            - 127.0.0.1:${DATABASE_PORT}:${DATABASE_PORT}
        volumes:
            - ./data/postgres:/data/postgres
        command: -p ${DATABASE_PORT}
    db_admin:
        image: dpage/pgadmin4:latest
        restart: unless-stopped
        environment:
            - PGADMIN_DEFAULT_EMAIL=${DB_ADMIN_EMAIL}
            - PGADMIN_DEFAULT_PASSWORD=${DB_ADMIN_PASSWORD}
        ports:
            - ${DB_ADMIN_PORT}:80
    db_backup:
      image: dashasmyr/db-guard:latest
      restart: unless-stopped
      environment:
          - HOST=db
          - PORT=${DATABASE_PORT}
          - USER=${DATABASE_USER}
          - PASSWORD=${DATABASE_PASSWORD}
          - DATABASE=${DATABASE_NAME}
          - MAX_BACKUP_COUNT=42 # keep one week
          - INTERVAL_SECONDS=14400 # every 4 hours
      volumes:
        - ./data/db_backups:/app/backups:rw
